name: Build and deploy React app to Azure Blob Storage

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  BACKEND_URL: pa200-hw02-backend-acbkcag9hzeec5hx.polandcentral-01.azurewebsites.net
  AZURE_STORAGE_CONTAINER: $web

jobs:
# ----------------------------------------------------------
# 1. BUILD
# ----------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Inject backend URL
        run: echo "REACT_APP_API_URL=$BACKEND_URL" >> .env

      - name: Build React app
        run: npm run build

      # Upload **the folder’s contents**
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: dist
          if-no-files-found: error

# ----------------------------------------------------------
# 2. DEPLOY
# ----------------------------------------------------------
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Put the files back into a fresh ./dist directory
      - name: Download build output into dist/
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: dist                       # <─ recreates the folder

      - name: Quick sanity-check
        run: tree -a dist

      - name: Deploy React app to Blob Storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --destination $AZURE_STORAGE_CONTAINER \
              --source dist \
              --overwrite
