name: Build and deploy JAR app to Azure Web App – pa200-hw02-backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: sports-reservation-system-backend

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload build artifact (all JARs in libs/)
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: sports-reservation-system-backend/build/libs
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List all downloaded files
        run: |
          echo "=== Directory tree ==="
          tree -a        # tree is pre-installed on Ubuntu runners
          echo
          echo "=== Found JARs ==="
          find . -type f -name "*.jar"

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: pa200-hw02-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'    
